[project]
name = "dao"
version = "0.1.0"
description = "A Convience Data Access Object"
authors = [
    { name = "Sandeep Evani", email = "sandeepevani01@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.2.3",
]

[project.scripts]
dao = "dao:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
